### ISSUE TITLE
Improve documentation for [MediaTypePreferences].comparePreference.

### ISSUE THREAD

**Issue by BlameOmar** [vapor/http#278]
[MediaTypePreferences].comparePreference creates an ordering from most to least preferred types. This is reasonable behavior but should be stated explicitly; I originally interpreted this method as comparing the quality values, which have the opposite ordering.

**Comment by tanner0101** [comment]
@BlameOmar are you referring to the API docs or guide docs? Would mind providing an idea of what a better explanation would look like?
