### ISSUE TITLE
Add support for SSL certificate validation

### ISSUE THREAD

**Issue by MrMage** [vapor/http#283]
Currently, `HTTPScheme.https` creates a TLS client configuration with `certificateVerification: .none`. There should be an option to enable certificate validation. If that requires the user to pass in extra trust roots, those could be passed in as an extra argument, e.g. like this:

    extension HTTPScheme {
        func makeHttps(certificateVerification: ..., trustRoot: ... = .default) -> HTTPScheme { ... }
    }

**Comment by tanner0101** [comment]
This has been fixed in [3.1.7](https://github.com/vapor/http/releases/tag/3.1.7)
