### ISSUE TITLE
HTTPCookies keys

### ISSUE THREAD

**Issue by marc-medley** [vapor/http#298]
**Problem:** I was unable to find a way to access `HTTPCookies` name `String` keys. Thus an apriori knowledge of such cookie name keys is required to retreive any cookie values.

**Expectation:** Since `HTTPCookies` is, in essence, similar to a `Dictionary` of _cookieName:cookieValue_ pairs, I had expected some access to the array of `keys`. And, also expected the standard Swift `for … in Dictionary …` iteration to work.

See "Iterating Over a Dictionary" section in [The Swift Programming Language](https://docs.swift.org/swift-book/LanguageGuide/CollectionTypes.html#ID113)

**Example:**

``` swift
let cookies: HTTPCookies = request.http.cookies

// keys: [String] style interation
for cookieName in cookies.keys {
    print("\(cookieName)=\(cookies[cookieName])")
}
// ERROR: Value of type 'HTTPCookies' has no member 'keys'

// direct Dictionary style interation
for (cookieName, cookieValue) in cookies {
    print("\(cookieName)=\(cookieValue)")
}
// ERROR: Type 'HTTPCookies' does not conform to protocol 'Sequence'
```

Attemps to add the capabilities via `extension HTTPCookies` failed because of the access restriction of `private var cookies: [String: HTTPCookieValue]` internal storage.

**Version:**  
HTTP version 3.0.7

**Comment by tanner0101** [comment]
There's a new, mutable property `HTTPCookies.all` that allows you to access the `[String: HTTPCookieValue]` data. This will be tagged in 3.1.0. Thanks!
