### ISSUE TITLE
Consider renaming or removing the Performance target

### ISSUE THREAD

**Issue by vzsg** [vapor/http#301]
It conflicts with other packages that chose the same, unfortunate name; most recently [noppoMan/Prorsum](https://github.com/noppoMan/Prorsum), which is a dependency of [swift-aws/aws-sdk-swift-core](https://github.com/swift-aws/aws-sdk-swift-core).

(That project hasn't been updated in a long while, so it's easier to change from this side.)

**Comment by tanner0101** [comment]
This will be renamed to `HTTPPerformance` in 3.1.0. Thanks for reporting!
