### ISSUE TITLE
Requests with "Connection: close" causes socket to be terminated too early

### ISSUE THREAD

**Issue by vzsg** [vapor/http#308]
Since HTTP 3.1.2, if a client sends a `Connection: close` header and the response would be "too large", the connection is terminated before the complete body is written to the socket.

On Heroku for example, this would result in a  `H18 Server Request Interrupted` error, and the clients will scream various Content-Length violation errors, for example:

```
HTTP load failing due to strict content length - expected: 990534, received: 314070, received (uncompressed): 0
```

HTTP 3.1.3 is also affected, **while 3.1.1 works as expected.**

### Steps to reproduce

1. Create a new Vapor app with the api-template.
1. Add the following route in routes.swift that generates 2 MBs of hex characters:
    ```swift
    router.get("big") { request -> String in
        return OSRandom().generateData(count: 1_000_000).hexEncodedString()
    }
    ```
1. Run the application:
    ```bash
    $ swift run    # or use Xcode :)
    ```
1. In another shell check that the app returns 2000000 bytes when called directly:
    ```bash
    $ curl -s localhost:8080/big | wc -c
        2000000
    $ curl -s localhost:8080/big | wc -c
        2000000
    $ curl -s localhost:8080/big | wc -c
        2000000
    $ curl -s localhost:8080/big | wc -c
        2000000
    ```
1. Then try the same with `Connection: close`:
    ```bash
    $ curl -H "Connection: close" -s localhost:8080/big | wc -c
        ???
    ```

### Expected behavior

The number of bytes returned should be 2M on every call.

### Actual behavior

The connection is terminated early. The number of bytes returned before the cutoff seems to depend the speed of the machine and the network connection.

(If your machine is too fast, increase the size of the random data.)

```
$ curl -s -H "Connection: close" localhost:8080/big | wc -c
  972187
$ curl -s -H "Connection: close" localhost:8080/big | wc -c
  261355
$ curl -s -H "Connection: close" localhost:8080/big | wc -c
  906651
$ curl -s -H "Connection: close" localhost:8080/big | wc -c
  261355
```

### Environment

* Vapor Framework version: 3.0.8 (HTTP 3.1.2-3)
* Vapor Toolbox version: N/A 
* OS version: macOS 10.13.6 locally, Ubuntu 16.04 on Heroku and in Docker

### Workaround

I've started recommending pinning HTTP to version 3.1.1.

```swift
.package(url: "https://github.com/vapor/http.git", .exact("3.1.1"))
```

**Comment by joscdk** [comment]
@tanner0101 this will make it easier to test through CircleCI :D

**Comment by tanner0101** [comment]
Looks like the problem was that `ctx.close(...)` was getting called synchronously after `ctx.write`. If the response was small enough, this didn't matter. 

#309 moves the close to be async (after the call to `ctx.writeAndFlush` signals success). 

The test added in #309 was failing with current code, and now works with the update. 

Thanks for reporting @vzsg!
