### ISSUE TITLE
Leaking promise in HTTPClientProtocolUpgrader.swift

### ISSUE THREAD

**Issue by mura-admin** [vapor/http#315]
Line 103 of HTTPClientProtocolUpgrader adds an upgrade promise to the event loop.

self.upgradePromise = worker.eventLoop.newPromise(Upgrader.UpgradeResult.self)

The deinit of the Future in NIO checks for unfulfilled promises and throws a fatalError if in debug.

Not sure how this could be better handled. Maybe adding a deinit to HTTPClientProtocolUpgrader? It seems to occur when the upgrader is unable to connect to the host but would be nice to have a more meaningful error in that case so that it can be used downstream.

**Comment by tanner0101** [comment]
Thanks for reporting this bug. I was also able to recreate it by attempting to connect to an invalid hostname. 

I've put up a PR here to fix the issue: https://github.com/vapor/http/pull/316
